### ISSUE TITLE
Implement Phase 1 ("The Grounds")

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/AztecChallenge#10]
**Task list**
- [x] Implement scrolling
- [x] Level design (with preliminary artwork)
- [x] Implement jumping
- [x] restart after collision
- [x] Life counter
- [ ] Score / Highscore counter
- [ ] Instant replay

---

Now that we have settled the most important questions, I'll try to implement "The Grounds" on the weekend. Attached you'll find my rough implementation concept. (Excel for the win! :+1: )

![implementation concept phase 1](https://cloud.githubusercontent.com/assets/22897030/19595056/5a96e922-9788-11e6-857d-6f4b5f86db21.png)

Any thoughts / remarks on that? And do you want to help me via Skype?

**Comment by t-karcher** [comment]
_Status update as of 2016-10-25_

**DONE**
* Game mechanics (scrolling, jumping etc.)
* Level design (with preliminary artwork)

**TODO**
* Life counter + restart after death
* Score / Highscore counter
* Instant replay
