### ISSUE TITLE
Add 2-Player mode

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/AztecChallenge#12]
**Task list**
- [x] move process handling to Stage (to prevent conflicts with camera handling, dying etc.)
- [x] outsource player node in separate scene
- [x] add custom export variables for life counter (nodePath) and inital x-value (int)
- [x] add two instances of player scene to Stage, set custom variables accordingly
- [x] in the Stage process handler, execute all player relevant code once or twice depending on the game mode:

```
var players = [get_node("P1")]
if mode == 2: players.append (get_node("P2"))
...
for p in players
```
